/**
 * Images should be stored in the `App/Images` directory and referenced using variables defined here.
 */

export default {
  avatar: require('../Assets/images/avatar.png'),
  product: require('../Assets/images/product.png'),
  product1: require('../Assets/images/product1.png'),
  product2: require('../Assets/images/product2.png'),
  product3: require('../Assets/images/product3.png'),
  product4: require('../Assets/images/product4.png'),
  product5: require('../Assets/images/product5.png'),
  flagVi: require('../Assets/images/vi.png'),
  flagEn: require('../Assets/images/en.png'),
  card: require('../Assets/images/Gold_Membership.png'),
  backgroundLogin: require('../Assets/images/background.png'),
  promotion1: require('../Assets/images/promotion1.png'),
  promotion2: require('../Assets/images/promotion2.png'),
  promotion3: require('../Assets/images/promotion3.png'),
  promotion4: require('../Assets/images/promotion4.png'),
  cod: require('../Assets/images/cod.png'),
  wallet: require('../Assets/images/wallet.png'),
  momo: require('../Assets/images/momo.png'),
  visa: require('../Assets/images/visa.png'),
  imageHeader: require('../Assets/images/imageHeader.png'),
  iconSanLuong: require('../Assets/images/IconSanLuong.png'),
  iconCalendar: require('../Assets/images/iconCalendar.png'),
  iconInvest: require('../Assets/images/iconInvest.png'),
  iconLand: require('../Assets/images/iconLand.png'),
  iconMoney: require('../Assets/images/iconMoney.png'),
  iconQuestion: require('../Assets/images/iconQuestion.png'),
  iconLike: require('../Assets/images/iconLike.png'),
  iconComment: require('../Assets/images/iconComment.png'),
  iconMaterial: require('../Assets/images/materialIcon.png'),
  iconMaterialTime: require('../Assets/images/materialTimeIcon.png'),
  iconMaterialMoney: require('../Assets/images/IconMaterialMoney.png'),
  iconTodoList: require('../Assets/images/IconTodoList.png'),
  iconNotifications: require('../Assets/images/notificationsIcon.png'),
  iconProcess: require('../Assets/images/iconProcess.png'),
}
